In [3]:
import numpy as np

dir_name = './weights_npy/'
layer_names = ['block1_conv1',
         'block1_conv2',
         'block2_conv1',
         'block2_conv2',
         'block3_conv1',
         'block3_conv2',
         'block3_conv3',
         'block4_conv1',
         'block4_conv2',
         'block4_conv3',
         'block5_conv1',
         'block5_conv2',
         'block5_conv3',
         'fc1',
         'fc2',
         'predictions']

In [4]:
for i in range(len(layer_names)):
    kernel = np.load(dir_name + layer_names[i] + 'kernel.npy')
    bias = np.load(dir_name + layer_names[i] + 'bias.npy')
    print kernel.shape
    print bias.shape

(64, 3, 3, 3)
(64,)
(64, 3, 3, 64)
(64,)
(128, 3, 3, 64)
(128,)
(128, 3, 3, 128)
(128,)
(256, 3, 3, 128)
(256,)
(256, 3, 3, 256)
(256,)
(256, 3, 3, 256)
(256,)
(512, 3, 3, 256)
(512,)
(512, 3, 3, 512)
(512,)
(512, 3, 3, 512)
(512,)
(512, 3, 3, 512)
(512,)
(512, 3, 3, 512)
(512,)
(512, 3, 3, 512)
(512,)
(25088, 4096)
(4096,)
(4096, 4096)
(4096,)
(4096, 1000)
(1000,)


In [5]:
import cv2
from matplotlib import pyplot as plt
import matplotlib.image as mpimg

im = cv2.resize(cv2.imread('persian_cat.jpg'), (224, 224)).astype(np.float32)

# im[:,:,0] -= 103.939
# im[:,:,1] -= 116.779
# im[:,:,2] -= 123.68
# im = im.transpose((2,0,1))
im = np.expand_dims(im, axis=0)
print im.shape
print im

(1, 224, 224, 3)
[[[[-102.93900299 -115.77899933 -122.68000031]
   [-102.93900299 -115.77899933 -122.68000031]
   [-103.93900299 -116.77899933 -123.68000031]
   ..., 
   [-101.93900299 -114.77899933 -121.68000031]
   [-101.93900299 -114.77899933 -121.68000031]
   [-102.93900299 -115.77899933 -122.68000031]]

  [[-102.93900299 -115.77899933 -122.68000031]
   [-102.93900299 -115.77899933 -122.68000031]
   [-103.93900299 -116.77899933 -123.68000031]
   ..., 
   [-101.93900299 -114.77899933 -121.68000031]
   [-101.93900299 -114.77899933 -121.68000031]
   [-102.93900299 -115.77899933 -122.68000031]]

  [[-102.93900299 -115.77899933 -122.68000031]
   [-102.93900299 -115.77899933 -122.68000031]
   [-103.93900299 -116.77899933 -123.68000031]
   ..., 
   [-101.93900299 -114.77899933 -121.68000031]
   [-101.93900299 -114.77899933 -121.68000031]
   [-102.93900299 -115.77899933 -122.68000031]]

  ..., 
  [[-103.93900299 -116.77899933 -123.68000031]
   [-102.93900299 -115.77899933 -122.68000031]
  

In [7]:
from layer_funcs import affine_forward, max_pool_forward, conv_forward, relu_forward

x = im
print x 

stride = 1

for i in range(0, 2):
    kernel = np.load(dir_name + layer_names[i] + 'kernel.npy')
    bias = np.load(dir_name + layer_names[i] + 'bias.npy')
    pad_width = 1
    x = conv_forward(x, kernel, bias, pad_width, stride)
    x, _ = relu_forward(x)
    print("layer{}".format(i))
    print(x.shape)
    print x
    
x = max_pool_forward(x, pool_size=2, stride=2)
print("maxpool")
print x.shape
print x


for i in range(2, 4):
    kernel = np.load(dir_name + layer_names[i] + 'kernel.npy')
    bias = np.load(dir_name + layer_names[i] + 'bias.npy')
    pad_width = 1
    x = conv_forward(x, kernel, bias, pad_width, stride)
    x, _ = relu_forward(x)
    print("layer{}".format(i))
    print(x.shape)
    print x
    
x = max_pool_forward(x, pool_size=2, stride=2)
print("maxpool")
print x.shape
print x

for i in range(4, 7):
    kernel = np.load(dir_name + layer_names[i] + 'kernel.npy')
    bias = np.load(dir_name + layer_names[i] + 'bias.npy')
    pad_width = 1
    x = conv_forward(x, kernel, bias, pad_width, stride)
    x, _ = relu_forward(x)
    print("layer{}".format(i))
    print(x.shape)
    print x
    
x = max_pool_forward(x, pool_size=2, stride=2)
print("maxpool")
print x.shape
print x

for i in range(7, 10):
    kernel = np.load(dir_name + layer_names[i] + 'kernel.npy')
    bias = np.load(dir_name + layer_names[i] + 'bias.npy')
    pad_width = 1
    x = conv_forward(x, kernel, bias, pad_width, stride)
    x, _ = relu_forward(x)
    print("layer{}".format(i))
    print(x.shape)
    print x
    
x = max_pool_forward(x, pool_size=2, stride=2)
print("maxpool")
print x.shape
print x

for i in range(10, 13):
    kernel = np.load(dir_name + layer_names[i] + 'kernel.npy')
    bias = np.load(dir_name + layer_names[i] + 'bias.npy')
    pad_width = 1
    x = conv_forward(x, kernel, bias, pad_width, stride)
    x, _ = relu_forward(x)
    print("layer{}".format(i))
    print(x.shape)
    print x
    
x = max_pool_forward(x, pool_size=2, stride=2)
print("maxpool")
print x.shape
print x

for i in range(13, 16):
    kernel = np.load(dir_name + layer_names[i] + 'kernel.npy')
    bias = np.load(dir_name + layer_names[i] + 'bias.npy')
    x, _ = affine_forward(x, kernel, bias)
    x, _ = relu_forward(x)
    print("layer{}".format(i))
    print x.shape
    print x

result = x

[[[[-102.93900299 -115.77899933 -122.68000031]
   [-102.93900299 -115.77899933 -122.68000031]
   [-103.93900299 -116.77899933 -123.68000031]
   ..., 
   [-101.93900299 -114.77899933 -121.68000031]
   [-101.93900299 -114.77899933 -121.68000031]
   [-102.93900299 -115.77899933 -122.68000031]]

  [[-102.93900299 -115.77899933 -122.68000031]
   [-102.93900299 -115.77899933 -122.68000031]
   [-103.93900299 -116.77899933 -123.68000031]
   ..., 
   [-101.93900299 -114.77899933 -121.68000031]
   [-101.93900299 -114.77899933 -121.68000031]
   [-102.93900299 -115.77899933 -122.68000031]]

  [[-102.93900299 -115.77899933 -122.68000031]
   [-102.93900299 -115.77899933 -122.68000031]
   [-103.93900299 -116.77899933 -123.68000031]
   ..., 
   [-101.93900299 -114.77899933 -121.68000031]
   [-101.93900299 -114.77899933 -121.68000031]
   [-102.93900299 -115.77899933 -122.68000031]]

  ..., 
  [[-103.93900299 -116.77899933 -123.68000031]
   [-102.93900299 -115.77899933 -122.68000031]
   [-101.93900299 -

maxpool
(1, 112, 112, 64)
[[[[  7.28469341e+02   7.86968063e+02   1.75858163e+02 ...,
      2.58689280e+02   0.00000000e+00   2.25605224e+02]
   [  4.10380203e+02   6.93765028e+02   1.57052020e+02 ...,
      2.25052729e+02   7.32113356e+01   1.24371609e+01]
   [  4.07222037e+02   6.93421235e+02   1.56839064e+02 ...,
      2.25192900e+02   7.56149447e+01   1.14790311e+01]
   ..., 
   [  3.99853063e+02   6.85644452e+02   1.56645486e+02 ...,
      2.22286972e+02   8.33372941e+01   1.24947083e+01]
   [  4.08995602e+02   6.85997594e+02   1.56650893e+02 ...,
      2.21898626e+02   8.11545392e+01   1.24468822e+01]
   [  7.09124495e+02   7.41392377e+02   1.61943414e+02 ...,
      2.65907615e+02   5.86163058e+02   2.15748930e+02]]

  [[  4.02308127e+02   6.11631549e+02   1.41302151e+02 ...,
      1.49791227e+02   1.03306953e+01   2.98534809e+01]
   [  0.00000000e+00   2.79653488e+02   1.01211421e+02 ...,
      2.43008095e+01   5.13434987e+00   0.00000000e+00]
   [  0.00000000e+00   2.77803563e+

maxpool
(1, 56, 56, 128)
[[[[  5.83561082e+02   4.10765459e+02   1.80921374e+02 ...,
      8.62016228e+02   7.14321132e+02   1.32182190e+02]
   [  5.71565111e+02   0.00000000e+00   0.00000000e+00 ...,
      6.20037894e+02   3.90354439e+02   1.93562353e+02]
   [  5.15308355e+02   0.00000000e+00   0.00000000e+00 ...,
      5.38487189e+02   3.97102931e+02   0.00000000e+00]
   ..., 
   [  5.07023806e+02   0.00000000e+00   0.00000000e+00 ...,
      6.17420460e+02   3.36596437e+02   0.00000000e+00]
   [  5.09696198e+02   0.00000000e+00   0.00000000e+00 ...,
      6.03635596e+02   7.70935120e+02   0.00000000e+00]
   [  5.47493934e+02   3.48753753e+02   2.61255436e+01 ...,
      7.62208134e+02   1.15928729e+03   0.00000000e+00]]

  [[  3.57506752e+02   4.17128813e-01   2.07864130e+02 ...,
      4.49071977e+02   6.50419001e+01   4.21739808e+02]
   [  2.63282328e+02   0.00000000e+00   1.09263746e+02 ...,
      2.12382421e+02   0.00000000e+00   4.92839978e+02]
   [  1.31149297e+02   0.00000000e+0

layer6
(1, 56, 56, 256)
[[[[ 118.05749929   27.03480534    0.         ...,  146.91608225
     180.79990409    0.        ]
   [   0.            0.            0.         ...,  329.42706759    0.
       0.        ]
   [   0.            0.            0.         ...,  322.1465999     0.
       0.        ]
   ..., 
   [   0.            0.            0.         ...,    0.            0.
       0.        ]
   [   0.            0.            0.         ...,   11.51017043    0.
       0.        ]
   [   0.           94.76066986    0.         ...,  368.14066983    0.
       0.        ]]

  [[   0.          343.79809398    0.         ...,    0.           21.36001923
       0.        ]
   [   0.            0.            0.         ...,    0.            0.
       0.        ]
   [   0.            0.            0.         ...,    0.            0.
       0.        ]
   ..., 
   [   0.            0.            0.         ...,    0.            0.
       0.        ]
   [   0.            0.            0.   

layer8
(1, 28, 28, 512)
[[[[   0.          307.20109911  347.23502984 ...,  152.68875224
     421.28090111    0.        ]
   [   0.          116.78033203  246.62259267 ...,    0.          401.65952801
       0.        ]
   [   0.           49.77296075  279.1295982  ...,    0.          221.30555182
       0.        ]
   ..., 
   [   0.          468.81511997    0.         ...,    0.          216.19200959
       0.        ]
   [   0.          419.08997649    0.         ...,    0.          215.80292966
       0.        ]
   [   0.          142.69945342  234.25521192 ...,   42.58641726
     317.62639648    0.        ]]

  [[   0.           54.21654715  260.06211622 ...,    0.          171.82394476
       8.26041106]
   [   0.            0.          119.51207658 ...,    0.            0.
       0.        ]
   [   0.            0.          183.99679277 ...,    0.            0.
       0.        ]
   ..., 
   [   0.          161.56765088    0.         ...,    0.            0.
       0.        ]


layer10
(1, 14, 14, 512)
[[[[   0.           51.11895283    0.         ...,    0.          296.91682739
      47.05145334]
   [   0.           25.52921974    0.         ...,    0.          160.97585207
      78.9792914 ]
   [   0.           18.47380089    0.         ...,   40.40294331
      96.58675294   39.17496155]
   ..., 
   [   0.           37.06408004    0.         ...,    2.58958759
     235.66852622    0.        ]
   [  29.506271     34.60044021    0.         ...,    0.          292.37057576
       0.        ]
   [ 107.12530402   39.34802591    0.         ...,    0.          333.40814256
       0.        ]]

  [[   0.            0.            0.         ...,    0.          205.46109666
      81.23608552]
   [   0.            0.            0.         ...,    0.           28.87185508
      97.81001245]
   [   0.            0.            0.         ...,    0.           14.53095194
      52.34185009]
   ..., 
   [   0.            0.            0.         ...,    0.            0.
  

layer13
(1, 4096)
[[  0.           0.          11.29686216 ...,   1.25872664   7.44431946
    0.        ]]
layer14
(1, 4096)
[[ 0.          0.          0.         ...,  3.76591228  0.          0.33631767]]
layer15
(1, 1000)
[[  0.00000000e+00   1.78088147e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00   1.04379893e+00   0.00000000e+00   1.76303645e+00
    2.97852908e+00   4.43262583e+00   0.00000000e+00   0.00000000e+00
    1.06872596e+00   1.93574986e+00   0.00000000e+00   1.24019247e+00
    2.26404873e+00   2.75446104e+00   1.74905780e+00   5.67863161e-01
    9.14750297e-01   4.17574773e+00   7.21777175e+00   2.75665985e+00
    3.46721613e+00   0.00000000e+00   0.00000000e+00   2.79404530e-01
    0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   4.55849493e-02   0.00000000e+00
    1.06435028e+00   0.00000000e+00   0.00000000e+00   5.23480066e-02
    2.

In [9]:
print np.argmax(result)
print result.shape
print result
print result[0][np.argmax(result)]

283
(1, 1000)
[[  0.00000000e+00   1.78088147e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00   1.04379893e+00   0.00000000e+00   1.76303645e+00
    2.97852908e+00   4.43262583e+00   0.00000000e+00   0.00000000e+00
    1.06872596e+00   1.93574986e+00   0.00000000e+00   1.24019247e+00
    2.26404873e+00   2.75446104e+00   1.74905780e+00   5.67863161e-01
    9.14750297e-01   4.17574773e+00   7.21777175e+00   2.75665985e+00
    3.46721613e+00   0.00000000e+00   0.00000000e+00   2.79404530e-01
    0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   4.55849493e-02   0.00000000e+00
    1.06435028e+00   0.00000000e+00   0.00000000e+00   5.23480066e-02
    2.28528619e+00   0.00000000e+00   2.19849445e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00   1.36431502e+00   1.42056544e-01   1.24845601e-01
    0.

In [10]:
from layer_funcs import softmax

sresult = softmax(result)
print sresult.shape
print np.argmax(sresult)
print sresult[0, np.argmax(sresult)]
print sresult

(1, 1000)
283
0.991050082148
[[  5.87152827e-08   3.48480235e-07   5.87152827e-08   5.87152827e-08
    5.87152827e-08   1.66750549e-07   5.87152827e-08   3.42316756e-07
    1.15427662e-06   4.94101411e-06   5.87152827e-08   5.87152827e-08
    1.70959384e-07   4.06852172e-07   5.87152827e-08   2.02936376e-07
    5.64956524e-07   9.22567998e-07   3.37564918e-07   1.03602681e-07
    1.46562263e-07   3.82168910e-06   8.00552094e-05   9.24598780e-07
    1.88167229e-06   5.87152827e-08   5.87152827e-08   7.76416939e-08
    5.87152827e-08   5.87152827e-08   5.87152827e-08   5.87152827e-08
    5.87152827e-08   5.87152827e-08   5.87152827e-08   5.87152827e-08
    5.87152827e-08   5.87152827e-08   6.14537583e-08   5.87152827e-08
    1.70212955e-07   5.87152827e-08   5.87152827e-08   6.18707822e-08
    5.77083074e-07   5.87152827e-08   5.29109019e-07   5.87152827e-08
    5.87152827e-08   5.87152827e-08   5.87152827e-08   5.87152827e-08
    5.87152827e-08   2.29755354e-07   6.76776904e-08   6.6522